---
# tasks file for bitbucket

- name: create system user
  user:
    name={{ bitbucket_user }}
    password={{ bitbucket_pass }}
    home={{ bitbucket_home }}
    system=yes
    shell=/bin/bash
  tags: bitbucket

- name: prepare directory
  file:
    path={{ item }}
    owner={{ bitbucket_user }}
    group={{ bitbucket_user }}
    state=directory
    mode=0755
  with_items:
    - "{{ bitbucket_catalina }}"
  tags: bitbucket

- name: download package
  get_url:
    url={{ bitbucket_url }}
    dest={{ bitbucket_archive }}
    sha256sum={{ bitbucket_sha256 }}
  tags: bitbucket

- name: unarchive package
  shell: tar zxvf {{ bitbucket_archive }} -C {{ bitbucket_catalina }} --strip-components=1; chown -Rf {{ bitbucket_user }}:{{ bitbucket_user }} {{ bitbucket_catalina }}
  args:
    creates: "{{ bitbucket_catalina }}/bin/start-bitbucket.sh"
  tags: bitbucket

- name: copy templates
  template:
    src="{{ item }}.j2"
    dest="/{{ item }}"
    owner={{ bitbucket_user }}
    group={{ bitbucket_user }}
    mode=0644
  with_items:
    - etc/init.d/bitbucket
    - usr/share/bitbucket/bin/setenv.sh
    - usr/share/bitbucket/conf/server.xml
  tags: bitbucket

- name: prepare service script
  file:
    path=/etc/init.d/bitbucket
    owner=root
    group=root
    state=file
    mode=0755
  tags: bitbucket

- name: enable service
  service: name=bitbucket enabled=yes
  notify: restart bitbucket
  tags: bitbucket
