---
# tasks file for hswong3i.bitbucket

- name: create group
  group:
    name: "{{ bitbucket_user }}"
    gid: "{{ bitbucket_gid | default(None) or omit }}"
  when: bitbucket_pass is string and bitbucket_hash_salt is string
  notify: restart bitbucket
  tags: hswong3i.bitbucket

- name: create user
  user:
    name: "{{ bitbucket_user }}"
    password: "{{ bitbucket_pass | password_hash('sha512', bitbucket_hash_salt) }}"
    home: "{{ bitbucket_home }}"
    group: "{{ bitbucket_user }}"
    uid: "{{ bitbucket_uid | default(None) or omit }}"
    shell: "/bin/bash"
  when: bitbucket_pass is string and bitbucket_hash_salt is string
  notify: restart bitbucket
  tags: hswong3i.bitbucket

- name: prepare files
  file:
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    state: "{{ item.state }}"
  with_items:
    - { dest: "{{ bitbucket_catalina }}", owner: "{{ bitbucket_user }}", group: "{{ bitbucket_user }}", mode: "0755", state: "directory" }
  notify: restart bitbucket
  tags: hswong3i.bitbucket

- name: download package
  get_url:
    url: "{{ bitbucket_url }}"
    dest: "/tmp/{{ bitbucket_archive }}"
    checksum: "{{ bitbucket_checksum }}"
  tags: hswong3i.bitbucket

- name: unarchive package
  shell: |
    tar zxvf /tmp/{{ bitbucket_archive }} -C {{ bitbucket_catalina }} --strip-components=1
    chown -Rf {{ bitbucket_user }}:{{ bitbucket_user }} {{ bitbucket_catalina }}
  args:
    creates: "{{ bitbucket_catalina }}/bin/start-bitbucket.sh"
  tags: hswong3i.bitbucket

- name: copy configs
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: "usr/share/bitbucket/bin/setenv.sh.j2", dest: "{{ bitbucket_catalina }}/bin/setenv.sh", owner: "{{ bitbucket_user }}", group: "{{ bitbucket_user }}", mode: "0644" }
    - { src: "usr/share/bitbucket/conf/server.xml.j2", dest: "{{ bitbucket_catalina }}/conf/server.xml", owner: "{{ bitbucket_user }}", group: "{{ bitbucket_user }}", mode: "0644" }
  notify: restart bitbucket
  tags: hswong3i.bitbucket

- name: copy init.d
  template:
    src: "etc/init.d/bitbucket.j2"
    dest: "/etc/init.d/bitbucket"
    owner: "root"
    group: "root"
    mode: "0755"
  when: 
    (ansible_os_family == 'Ubuntu')
  tags: hswong3i.bitbucket

- name: copy init systemd
  template:
    src: "etc/systemd/system/bitbucket.j2"
    dest: "/etc/systemd/system/bitbucket.service"
    owner: "root"
    group: "root"
    mode: "0755"
  when: 
    (ansible_os_family == 'RedHat' and ansible_distribution_version >= '7') or 
    (ansible_os_family == 'CentOS' and ansible_distribution_version >= '7') or 
    (ansible_os_family == 'Debian' and ansible_distribution_version >= '7') or
    (ansible_os_family == 'Fedora' and ansible_distribution_version >= '15') 
  tags: hswong3i.bitbucket

- name: reload systemd
  systemd: name=bitbucket daemon_reload=yes
  when: 
    (ansible_os_family == 'RedHat' and ansible_distribution_version >= '7') or 
    (ansible_os_family == 'CentOS' and ansible_distribution_version >= '7')

- name: enable service
  service:
    name: "bitbucket"
    enabled: "yes"
  notify: restart bitbucket
  tags: hswong3i.bitbucket
